version: "3.7"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  app:
    build: .
    environment:
      RACK_ENV: "${RACK_ENV}"
      SEED_BROKERS: "kafka:9092"
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/src/app
    command: bin/coin_api_metadata start
    depends_on:
      - kafka
